services:
  - type: web
    name: real-time-poll-rooms
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: PORT
        value: 5000
